[versions]
accompanist = "0.29.1-alpha"
composeCompiler = "1.4.3"
composeConstraintLayout = "1.1.0-alpha08"
glm = "0.9.9.1-5"
kotlin = "1.7.21"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-compose-activity = "androidx.activity:activity-compose:1.7.0-beta01"
androidx-compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.0" }
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha18"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.0"
coil-compose = "io.coil-kt:coil-compose:2.2.2"
graphics-glm = { module = "kotlin.graphics:glm", version.ref = "glm" }
lottie-compose = "com.airbnb.android:lottie-compose:6.0.0"
skydoves-orbital = "com.github.skydoves:orbital:0.2.4"
timber = "com.jakewharton.timber:timber:5.0.1"
konfetti = "nl.dionsegijn:konfetti-compose:2.0.2"