[versions]
accompanist = "0.36.0"
androidPlugin = "9.5.0-alpha04"
androidx-activity-compose = "1.13.0"
androidx-compose-bom = "2026.08.01"
androidx-media = "1.11.0"
barcodeScanning = "17.3.0"
camera = "1.7.0-alpha03"
composeConstraintLayout = "1.1.2"
glm = "0.9.9.1-11"
gradleVersions = "0.61.0"
haze = "1.7.3"
kotlin = "2.4.20-RC3"
material-icons = "1.7.8"
material3 = "1.5.0-alpha27"

[libraries]
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material3", version.ref = "accompanist" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
androidx-camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "camera" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
androidx-compose-bom = { module = "androidx.compose:compose-bom-alpha", version.ref = "androidx-compose-bom" }
androidx-compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material-icons" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.19.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.11.0" }
androidx-media-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media" }
androidx-media-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.2.0"
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
captureable = "dev.shreyaspatil:capturable:3.0.1"
coil-compose = "io.coil-kt:coil-compose:2.7.0"
graphics-glm = { module = "kotlin.graphics:glm", version.ref = "glm" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
konfetti = "nl.dionsegijn:konfetti-compose:2.1.0-beta01"
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
lottie-compose = "com.airbnb.android:lottie-compose:6.7.1"
physics-layout = "io.github.klassenkonstantin:physics-layout:0.4.1"
timber = "com.jakewharton.timber:timber:5.0.1"
zoomable = "net.engawapg.lib:zoomable:2.13.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
ben-manes-versions = { id = "io.github.ben-manes.versions", version.ref = "gradleVersions" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }