[versions]
accompanist = "0.33.1-alpha"
colorpickerCompose = "1.0.4"
composeCompiler = "1.5.3"
composeConstraintLayout = "1.1.0-alpha12"
datastorePreferences = "1.1.0-alpha04"
glm = "0.9.9.1-5"
kotlinxSerializationJson = "1.6.0-RC"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material3", version.ref = "accompanist" }
androidx-compose-activity = "androidx.activity:activity-compose:1.8.0-alpha07"
androidx-compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0-rc01" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.7.0-alpha01" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.1.0-alpha01"
coil-compose = "io.coil-kt:coil-compose:2.4.0"
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
graphics-glm = { module = "kotlin.graphics:glm", version.ref = "glm" }
konfetti = "nl.dionsegijn:konfetti-compose:2.0.3"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lottie-compose = "com.airbnb.android:lottie-compose:6.1.0"
skydoves-orbital = "com.github.skydoves:orbital:0.2.4"
timber = "com.jakewharton.timber:timber:5.0.1"