[versions]
accompanist = "0.33.0-alpha"
composeCompiler = "1.5.1"
composeConstraintLayout = "1.1.0-alpha12"
glm = "0.9.9.1-5"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material3", version.ref = "accompanist" }
androidx-compose-activity = "androidx.activity:activity-compose:1.8.0-alpha06"
androidx-compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0-rc01" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.7.0-alpha01" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.1.0-alpha01"
coil-compose = "io.coil-kt:coil-compose:2.4.0"
graphics-glm = { module = "kotlin.graphics:glm", version.ref = "glm" }
lottie-compose = "com.airbnb.android:lottie-compose:6.1.0"
skydoves-orbital = "com.github.skydoves:orbital:0.2.4"
timber = "com.jakewharton.timber:timber:5.0.1"
konfetti = "nl.dionsegijn:konfetti-compose:2.0.3"