[versions]
accompanist = "0.26.1-alpha"
compose = "1.2.0-rc01"
composeAnimationGraphics = "1.3.0-alpha03"
composeCompiler = "1.3.0"
composeMaterial3 = "1.0.0-alpha16"
composeMaterialIcons = "1.3.0-alpha03"
composeUi = "1.3.0-alpha03"
composeUiTooling = "1.3.0-alpha02"
kotlin = "1.7.10"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
coilCompose = "io.coil-kt:coil-compose:1.4.0"
composeActivity = "androidx.activity:activity-compose:1.6.0-beta01"
composeAnimation = { module = "androidx.compose.animation:animation", version = "compose" }
composeAnimationGraphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "composeAnimationGraphics" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
composeMaterialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterialIcons" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version = "2.5.0-alpha02" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiTooling" }
constraintCompose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.0" }
coreKtx = { module = "androidx.core:core-ktx", version = "1.9.0-beta01" }
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.0-alpha01" }
pagingCompose = "androidx.paging:paging-compose:1.0.0-alpha14"