[versions]
compose = "1.2.0-alpha03"
composeCompiler = "1.2.0-alpha06"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version = "1.8.0-alpha04" }
lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.0-alpha05"
# compose
composeActivity = "androidx.activity:activity-compose:1.6.0-alpha01"
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
composeAnimation = { module = "androidx.compose.animation:animation", version = "compose" }
composeAnimationGraphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha05" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version = "2.5.0-alpha02" }
constraintCompose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.0" }
pagingCompose = "androidx.paging:paging-compose:1.0.0-alpha14"
coilCompose = "io.coil-kt:coil-compose:1.4.0"