[versions]
accompanist = "0.27.0"
compose = "1.4.0-alpha01"
composeAnimation = "1.4.0-alpha01"
composeAnimationGraphics = "1.4.0-alpha01"
composeCompiler = "1.3.2"
composeConstraintLayout = "1.1.0-alpha04"
composeMaterial3 = "1.1.0-alpha01"
composeMaterialIcons = "1.4.0-alpha01"
composeUi = "1.4.0-alpha01"
composeUiTooling = "1.4.0-alpha01"
kotlin = "1.7.20"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-compose-activity = "androidx.activity:activity-compose:1.7.0-alpha02"
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "composeAnimation" }
androidx-compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "composeAnimationGraphics" }
androidx-compose-constraint = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterialIcons" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.5.0-alpha02" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiTooling" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.0-alpha03" }
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha14"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.0"
coil-compose = "io.coil-kt:coil-compose:2.2.2"
lottie-compose = "com.airbnb.android:lottie-compose:5.2.0"
skydoves-orbital = "com.github.skydoves:orbital:0.2.2"
timber = "com.jakewharton.timber:timber:5.0.1"