[versions]
compose = "1.2.0-rc01"
composeCompiler = "1.2.0"
composeAnimationGraphics = "1.3.0-alpha01"
composeMaterialIcons = "1.3.0-alpha01"
composeMaterial3 ="1.0.0-alpha14"
composeUi = "1.3.0-alpha01"
composeUiTooling = "1.3.0-alpha01"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version = "1.9.0-alpha05" }
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version ="2.6.0-alpha01" }
# compose
composeActivity = "androidx.activity:activity-compose:1.6.0-alpha05"
composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
composeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiTooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiTooling" }
composeAnimation = { module = "androidx.compose.animation:animation", version = "compose" }
composeAnimationGraphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "composeAnimationGraphics" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterialIcons" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version = "2.5.0-alpha02" }
constraintCompose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.0" }
pagingCompose = "androidx.paging:paging-compose:1.0.0-alpha14"
coilCompose = "io.coil-kt:coil-compose:1.4.0"