package de.nilsdruyen.composeparty.settings.component

import androidx.compose.material3.ColorScheme


internal fun Map<String, String>.toScheme(): ColorScheme = ColorScheme(
    primary = getOrDefault("primary", "#FFFFFF").toColor(),
    onPrimary = getOrDefault("onPrimary", "#FFFFFF").toColor(),
    primaryContainer = getOrDefault("primaryContainer", "#FFFFFF").toColor(),
    onPrimaryContainer = getOrDefault("onPrimaryContainer", "#FFFFFF").toColor(),
    inversePrimary = getOrDefault("inversePrimary", "#FFFFFF").toColor(),
    secondary = getOrDefault("secondary", "#FFFFFF").toColor(),
    onSecondary = getOrDefault("onSecondary", "#FFFFFF").toColor(),
    secondaryContainer = getOrDefault("secondaryContainer", "#FFFFFF").toColor(),
    onSecondaryContainer = getOrDefault("onSecondaryContainer", "#FFFFFF").toColor(),
    tertiary = getOrDefault("tertiary", "#FFFFFF").toColor(),
    onTertiary = getOrDefault("onTertiary", "#FFFFFF").toColor(),
    tertiaryContainer = getOrDefault("tertiaryContainer", "#FFFFFF").toColor(),
    onTertiaryContainer = getOrDefault("onTertiaryContainer", "#FFFFFF").toColor(),
    background = getOrDefault("background", "#FFFFFF").toColor(),
    onBackground = getOrDefault("onBackground", "#FFFFFF").toColor(),
    surface = getOrDefault("surface", "#FFFFFF").toColor(),
    onSurface = getOrDefault("onSurface", "#FFFFFF").toColor(),
    surfaceVariant = getOrDefault("surfaceVariant", "#FFFFFF").toColor(),
    onSurfaceVariant = getOrDefault("onSurfaceVariant", "#FFFFFF").toColor(),
    surfaceTint = getOrDefault("surfaceTint", "#FFFFFF").toColor(),
    inverseSurface = getOrDefault("inverseSurface", "#FFFFFF").toColor(),
    inverseOnSurface = getOrDefault("inverseOnSurface", "#FFFFFF").toColor(),
    error = getOrDefault("error", "#FFFFFF").toColor(),
    onError = getOrDefault("onError", "#FFFFFF").toColor(),
    errorContainer = getOrDefault("errorContainer", "#FFFFFF").toColor(),
    onErrorContainer = getOrDefault("onErrorContainer", "#FFFFFF").toColor(),
    outline = getOrDefault("outline", "#FFFFFF").toColor(),
    outlineVariant = getOrDefault("outlineVariant", "#FFFFFF").toColor(),
    scrim = getOrDefault("scrim", "#FFFFFF").toColor(),
)

internal fun ColorScheme.toMap(): Map<String, String> = mapOf(
    "primary" to primary.raw(),
    "onPrimary" to onPrimary.raw(),
    "primaryContainer" to primaryContainer.raw(),
    "onPrimaryContainer" to onPrimaryContainer.raw(),
    "inversePrimary" to inversePrimary.raw(),
    "secondary" to secondary.raw(),
    "onSecondary" to onSecondary.raw(),
    "secondaryContainer" to secondaryContainer.raw(),
    "onSecondaryContainer" to onSecondaryContainer.raw(),
    "tertiary" to tertiary.raw(),
    "onTertiary" to onTertiary.raw(),
    "tertiaryContainer" to tertiaryContainer.raw(),
    "onTertiaryContainer" to onTertiaryContainer.raw(),
    "background" to background.raw(),
    "onBackground" to onBackground.raw(),
    "surface" to surface.raw(),
    "onSurface" to onSurface.raw(),
    "surfaceVariant" to surfaceVariant.raw(),
    "onSurfaceVariant" to onSurfaceVariant.raw(),
    "surfaceTint" to surfaceTint.raw(),
    "inverseSurface" to inverseSurface.raw(),
    "inverseOnSurface" to inverseOnSurface.raw(),
    "error" to error.raw(),
    "onError" to onError.raw(),
    "errorContainer" to errorContainer.raw(),
    "onErrorContainer" to onErrorContainer.raw(),
    "outline" to outline.raw(),
    "outlineVariant" to outlineVariant.raw(),
    "scrim" to scrim.raw(),
)