name: Build apk

on:
  push:
    branches:
      - main
      - develop
      - renovate/**

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_release_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build release apk
        run: ./gradlew :app:assembleRelease
